### ISSUE TITLE
what are the differences betwen these two ?

### ISSUE THREAD

**Issue by geraldodev** [henryw374/chronos#1]
![image](https://user-images.githubusercontent.com/774408/161740294-b0a5b327-166f-4743-927e-bceaa1d5b6bc.png)

I assume that the first option already polyfills because there are no instruction to do so, but the quality is low ? is that right ?

Using the second option affects build size ? The quality is higher but It adds weight to build size

Thank you for helping making cljs match js in quality of libraries.

Geraldo

**Comment by henryw374** [comment]
Hi. With both versions you have to include the Temporal API yourself, either via npm or cdn. It is not available in any browser as far as I am aware. I've kind of put this project on the back burner for now until I see that happening.

Neither version, first or second is 'ready' in any sense. I should make that clearer on the readme
